// Generated by https://quicktype.io

export interface Locations {
    locations: Location[];
}

export interface Location {
    timestampMs:       string;
    latitudeE7:        number;
    longitudeE7:       number;
    accuracy:          number;
    activity?:         LocationActivity[];
    altitude?:         number;
    verticalAccuracy?: number;
}

export interface LocationActivity {
    timestampMs: string;
    activity:    ActivityActivity[];
}

export interface ActivityActivity {
    type:       Type;
    confidence: number;
}

export enum Type {
    InFourWheelerVehicle = "IN_FOUR_WHEELER_VEHICLE",
    InRailVehicle = "IN_RAIL_VEHICLE",
    InRoadVehicle = "IN_ROAD_VEHICLE",
    InTwoWheelerVehicle = "IN_TWO_WHEELER_VEHICLE",
    InVehicle = "IN_VEHICLE",
    OnBicycle = "ON_BICYCLE",
    OnFoot = "ON_FOOT",
    Still = "STILL",
    Tilting = "TILTING",
    Unknown = "UNKNOWN",
    Walking = "WALKING",
}
